/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,jsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#ffb3ae",
        "primary-container": "#c1272d",
        "on-primary": "#68000b",
        "on-primary-container": "#ffdbd8",
        "secondary": "#b3c5ff",
        "secondary-container": "#2a4386",
        "tertiary": "#cdcd00",
        "tertiary-container": "#b1b100",
        "background": "#131314",
        "surface": "#131314",
        "surface-dim": "#131314",
        "surface-bright": "#393939",
        "surface-container-lowest": "#0e0e0e",
        "surface-container-low": "#1b1c1c",
        "surface-container": "#1f2020",
        "surface-container-high": "#2a2a2a",
        "surface-container-highest": "#343535",
        "on-surface": "#e4e2e2",
        "on-surface-variant": "#e3bebb",
        "outline": "#aa8986",
        "outline-variant": "#5a403e",
        "on-background": "#e4e2e2",
        "on-secondary": "#0d2c6e",
        "on-tertiary": "#323200",
        "error": "#ffb4ab",
        "error-container": "#93000a",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "inverse-surface": "#e4e2e2",
        "inverse-on-surface": "#303030",
        "inverse-primary": "#b71f27",
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
      },
    },
  },
  plugins: [],
}